version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  # web:
  #   build: .
  #   volumes:
  #     - .:/yummy
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
